[package]
name = "poopnugget142/poopy"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Stew = "data-oriented-house/stew@2.2.1"
Signal = "sleitnick/signal@1.3.0"