[package]
name = "poopnugget142/poopy"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Stew = "data-oriented-house/rbxstew@0.3.1"
Signal = "sleitnick/signal@1.3.0"
Promise = "evaera/promise@4.0.0"
Cmdr = "evaera/cmdr@1.12.0"